### PR TITLE
color selector

### PR DESCRIPTION
**Pull request by skolerst**
Added color selector

### CODE REVIEW

**Comment by skolerst** [comment]
Referencing issue #16

**Comment by anishsujanani** [comment]
I've submitted a PR referencing the same issue a few minutes ago.

**Comment by sleddog** [comment]
Thanks for this.  Can you incorporate this free form txt box in addition to the selector that asi7296 added?

**Comment by skolerst** [comment]
meaning you want the user to be able to (for example) type in a color (or hex code?) and then it will get set that way?

**Comment by sleddog** [comment]
Hmmm... I just deployed up the color picker to the devingray.com/pool  take a look and see if you can improve upon it.  Otherwise, we can close this PR and you can grab another.

Oh it only changes the bumber felt, not the table felt... you could do that with this PR.

**Comment by skolerst** [comment]
you checked the one that asi7296 did? and he did just the bumpers? my code does the table (the light green color not the dark green)

**Comment by sleddog** [comment]
Ok.  Can you resolve the merge conflict?

**Comment by skolerst** [comment]
done

**Pull request merged**
