### PR TITLE
Issue #17: Object ball trajectory preview

### PR DESCRIPTION
**Pull request by kuper-adrian**
I implemented issue #17.

ball_trajectory_preview

Works pretty good, I think. Sometimes the object ball trajectory angle feels somewhat off, but nothing to bad. 

Besides: Is the used math library [math.js](http://mathjs.org/)? I wasn't sure, so I implemented a lot of helper functions for vector magnitude, dot product, etc. by myself 😄  I probably should rewrite my code to use the library functions before a potential merge, to keep things consistent and fast.

Additions and deletions look so bad because I ran an auto formatting tool out of bad habit. Will revert this, if this is a problem.

### CODE REVIEW

**Comment by sleddog** [comment]
@RiotOfViolence awesome stuff!  I just merged 2 PR's, so this is conflicted a little.  Can you resolve these conflicts and repush?

**Comment by kuper-adrian** [comment]
Sure thing. Will do after work

**Comment by sleddog** [comment]
thanks @RiotOfViolence - I think a followup task would be to consolidate/merge those new math functions you added with the math library.

**Comment by kuper-adrian** [comment]
Hey @sleddog! So the math library is self written for this game and not some popular framework with documentation, right? Anyways, I will look into it and see which of my math functions can be replaced by the library and which ones can be added.

And by the way: Thanks for doing this fun little project for Hacktoberfest and GitHub newcomers 😁

**Pull request merged**
