### PR TITLE
Added Power Bar for Shot Strength + Minor HTML Changes

### PR DESCRIPTION
**Pull request by ryanimpey**
Added power bar from issue #11. Also added some minor HTML changes to style control and colour area.

**What is the purpose of this Pull Request ?**
Added requested feature #11 where a power bar can be used to change the shot strength

**How is it achieved?**
Velocity of white ball is changed when the power bar is used to slider power up or down. Clicking on the table to set velocity will also change the power bar value and vice-versa. The power bar can set the velocity at any value between 0 and 100.

### CODE REVIEW

**Comment by sleddog** [comment]
This is great!  Is the power slider image an 8 ball?  shouldn't it be a cue ball?

**Comment by sleddog** [comment]
sorry, but @ryanimpey can you resolve merge conflicts?

**Comment by ryanimpey** [comment]
@sleddog I can change it to a white ball if wanted, just thought the 8 ball would look nicer but I understand your point! I'll check them now

**Comment by ryanimpey** [comment]
Fixed conflict

**Comment by sleddog** [comment]
thanks @ryanimpey can you switch it from an 8 ball, to a cue ball with those red dots?

**Comment by ryanimpey** [comment]
@sleddog Should now be a white ball with a red dot! Let me know if it looks right or if it still needs changing!

**Comment by sleddog** [comment]
@ryanimpey is the images/slider_image.png needed?  it is still showing as an 8ball

**Comment by ryanimpey** [comment]
Good point, I'll remove that now

**Comment by ryanimpey** [comment]
Removed images/slider_image.png. Directory was empty so also removed directory to avoid clutter.

**Comment by sleddog** [comment]
@ryanimpey this is great, but I think anything over a value of 50 is just crazy fast.  Also, think you could squeeze this powerbar up inline with the other controls?  I have to scroll down to view the power bar.

**Comment by ryanimpey** [comment]
@sleddog I'll make the max value for the slider 50 and move it onto the same line for you when I get the chance

**Pull request merged**
