### PR TITLE
#16 update: ability to change felt color

### PR DESCRIPTION
**Pull request by sagarchoudhary96**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@sleddog please see to it

**Comment by sleddog** [comment]
@sagarchoudhary96 can you resolve conflicts?

**Comment by sagarchoudhary96** [comment]
seems like some issue in layout let me commit with new changes!

**Comment by sagarchoudhary96** [comment]
@sleddog Everything Fixed Now. Please Review the PR again :)

**Comment by sagarchoudhary96** [comment]
@sleddog see to it please

**Comment by sleddog** [comment]
@sagarchoudhary96 for this and its merged.  It is now no longer possible to change the bumper color now.  Wanna take a crack at making it even better?

**Pull request merged**
