### PR TITLE
Determine Stripe or Solid

### PR DESCRIPTION
**Pull request by eclecticexistential**
Updated files for legibility. Linked to files for improved organization. Updated code to reward the user for hitting only stripes or solids in. Alert to let the user know if they won or lost based on this logic. Accounted for 8-ball as well.

### CODE REVIEW

**Comment by sleddog** [comment]
@eclecticexistential this is great work!  can you resolve the conflicts and i'll merge this puppy.

**Comment by eclecticexistential** [comment]
Resolved conflicts.

**Comment by sleddog** [comment]
sorry @eclecticexistential i merged another PR, can you resolve again?  I'll merge this quick

**Comment by sleddog** [comment]
@eclecticexistential the separate JS file was causing some caching issues, also I want to rethink the game logic a bit more to show some status on screen as opposed to an alert dialog.

**Pull request merged**
